ow2-proactive/studio

app/scripts/proactive/config.js
app/templates/04_native_task.xml

This patch closes ow2-proactive/scheduling#2288.

Merge native Linux and Windows workflow examples 

---

app/templates/script_docker_compose.xml

Add the docker-compose example.

Add the docker-compose example.

---

app/scripts/proactive/model/BranchWithScript.js

630+fix190

---

test/scripts/takeScreenshots.sh
test/ui/specs/forkExecutionEnvironment.js

Fix the studio tests.
Add a screenshot script which allows to "debug" the scripts better.

addTimeoutToClickForkEnv

---

app/scripts/proactive/templates/task-template.html

Allow parallel environments with numberOfNodes=1
Parallel environments can have 1 node.

Allow parallel environments with numberOfNodes=1

---

app/scripts/proactive/templates/script-template.html

added jugdement for language to avoid skipping

fixes #222 : Language type is lost if Script is cleared 

---

app/scripts/proactive/app.js
app/scripts/proactive/model/Job.js
app/scripts/proactive/model/SchemaModel.js
app/scripts/proactive/templates/script-template.html
app/scripts/proactive/view/WorkflowView.js

By allowing the override of the existing parts.

fixes #254: Job priority is lost when a workflow is imported

---

app/index.html
app/scripts/proactive/view/LogoutView.js

By click on logo open main site, put logout icon on right in button

By click on logo open main site, put logout icon on right in button

---

app/scripts/proactive/templates/task-template.html

I changed their order in task template

fixes #264: change the order of fork environment and pre-script

---

app/scripts/proactive/model/Script.js

I just removed "Cron Task" in the model of Script

fixes #266: remove Cron Task in the model of Script

---

app/index.html

We add a button for cloud automation, which makes the navigation bar larger than before, that's why it is overlap with the body.

fixes #270 Issues when resizing the browser window

---

app/templates/webnotification.xml

Improve webhook template:
- Standard method is POST
- Standard URL value is localhost:8080
- add json content for notification service

Improve webhook template:

---

app/templates/webnotification.xml

Fix web notification template

---

README.md

FixBuildIcon

---

app/scripts/proactive/config.js
app/templates/web_validation.xml
package.json

Python task that pauses its job and send a  notification validation message to the notification-service

New WebValidation task in Manual tasks

---

app/scripts/proactive/model/Task.js
app/scripts/proactive/view/ViewWithProperties.js

- Tasks.js: line 296 is added (fork environment tooltip)
- ViewWithProperties.js: line 230 is replaced by lines 230 to 234 (tooltip display bugfix). All tab tooltips are now correcly displayed

Tooltip management

---

app/index.html
test/ui/commands/checkExport.js
test/ui/commands/clickClearWorkflow.js
test/ui/commands/clickCloseWorkflow.js
test/ui/commands/clickSaveWorkflow.js
test/ui/commands/openDropdown.js
test/ui/specs/login.js

- Sub menus added
- Tests have been changed to use the sub menus

Add sub menus

---

app/scripts/proactive/view/TaskView.js

https://github.com/ow2-proactive/studio/issues/293

Bugfix #293

---

app/templates/web_validation.xml

@ow2-proactive/developers  two reviews please

Changes in web validation template to use scheduler api

---

README.md

Improve test documentation

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/model/utils.js
app/scripts/proactive/templates/task-template.html
app/styles/studio.css

Correct missing XML task variables part
Studio variables improvement

Task variables studio improvement

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js

- Add tooltips to Task and Job variables panels
- Clarify Task variables fields

Studio variables improvements

---

app/scripts/proactive/app.js
app/scripts/proactive/config.js
app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js

- documentation link is added in the job & task variables GUI.

Variables Model : add documentation link

---

app/scripts/proactive/templates/job-variable-template.html
app/scripts/proactive/view/dom.js

- add model attribute to the submission form and reuse it when building the workflow

issue when submitting job, model value was set to null for job variables

---

app/index.html
app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/rest/studio-client.js
app/scripts/proactive/templates/job-variable-template.html
app/scripts/proactive/view/dom.js
app/styles/studio.css

- added an option to send a rest call in synchronous mode
- use backbone form validation when changing variables in Job and Task
- use validation as well when submitting job using jquery modal window
- added model value to submission form and resized it for clarity

Quality Check: validate workflow while editing variables

---

app/index.html
app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/templates/job-template.html
app/scripts/proactive/templates/job-variable-template.html
app/scripts/proactive/templates/task-template.html
app/scripts/proactive/view/dom.js

- check button allows to validate the current variables and eventually update them with the server-side validation plugin
- also added task variables in submission form

QualityCheck: add check button in submission form

---

app/scripts/proactive/templates/job-template.html

Escape Generic Information

---

app/scripts/proactive/config.js
app/scripts/proactive/rest/studio-client.js

Rename exec scheduler to job planner

Rename exec scheduler to job planner

---

app/scripts/proactive/model/CatalogBucketCollection.js
app/scripts/proactive/model/CatalogWorkflowCollection.js
package-lock.json

make the workflow catalog portal show more than 20 buckets and workflows

cherry-picked from 7.28.3

---

app/scripts/proactive/rest/studio-client.js

Update the post on /job-planner/planned-jobs/ to comply with the new API

Update the post on /job-planner/planned-jobs/ to comply with the API 

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/rest/studio-client.js

Removed a line that doesn't make sense in file studio-client.js. Now the error alert in the popup is no longer blocked.

fix issue #387

---

app/scripts/proactive/editor/Link.js
app/scripts/proactive/model/Job.js

- Update URL format
- Update corresponding documentation

Update documentation link and corresponding url

---

app/scripts/proactive/view/dom.js

So the generic info with groups will be added automatically to current workflow in the studio.

when publish new wf to catalog, refresh - get wf from catalog as current wf

---

app/scripts/proactive/model/Job.js
app/styles/studio.css

Resize editable job description field and keep the task script area as it is

 Resize editable Job Description field

---

app/templates/SubmitJobAndWait.xml
app/templates/SubmitJobNoWait.xml

Change template to work with secure catalog

Change template to work with secure catalog

---

app/scripts/proactive/view/CatalogPublishView.js

Fix a bug from studio creating the new revisions of wf in catalog

---

app/index.html
app/scripts/proactive/model/Task.js
app/styles/studio.css
test/ui/specs/breadcrumb.js

Input for task name and task boxes with minimum and maximum sizes

Tasks with longer names improved

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/view/ViewWithProperties.js
app/styles/studio.css

Add and remove buttons more visible on the properties panel

Add and Remove buttons improvements

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js

Message asking user if he really wants to remove the property

Confirmation when removing properties (workflow variables, GI...)

---

build.gradle
gradle.properties

Reverts ow2-proactive/studio#438

Revert "Allow to change logo in studio"

---

app/index.html
app/scripts/proactive/app.js
app/scripts/proactive/router.js
app/scripts/proactive/templates/catalog-set-templates-bucket.html
app/scripts/proactive/templates/workflow-list.html
app/scripts/proactive/view/CatalogSetTemplatesBucketView.js
app/scripts/proactive/view/PaletteView.js
app/scripts/proactive/view/ViewWithProperties.js
app/scripts/proactive/view/WorkflowListView.js
app/scripts/proactive/view/WorkflowView.js
app/scripts/proactive/view/dom.js
app/studio-conf.js
app/styles/studio.css
gradle.properties

Removing local templates (url /studio/#templates not available anymore)
Removable extra templates menu
New item in Catalog menu to open extra templates menus
Pointer cursor for catalog menu tables
Change palettes position to absolute when dragged (-> no more white space in menu)

Removable extra template menu

---

app/scripts/proactive/templates/script-template.html

- latest changes created an issue when using empty scripts with a defined language. This change allows to be backward compatible

fix handling of empty script

---

test/json-server-data/buckets-resources/bucket-id-1000-res.json
test/json-server-data/objects-revisions/2min-cron-rev.json
test/json-server-data/objects-revisions/cloud-automation-rev.json
test/json-server-data/objects-revisions/data-mgnt-rev.json
test/json-server-data/objects-revisions/distrib-comput-rev.json
test/json-server-data/objects-revisions/docker-exec-env-rev.json

/cloud-automation url doesn't exist anymore with the dashboard

Updating pca.action.icon value for automation dashboard

---

app/index.html

Replacing link to cloud automation to automation dashboard & removing link to notification portal

Updating links to other portals

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/rest/studio-client.js
app/scripts/proactive/view/WorkflowListView.js
app/scripts/proactive/view/dom.js
test/spec/ImportExport.js
test/ui/commands/closeNotification.js

In this PR: 
We disable importing existing GI (`workflow.icon, Documentation, bucketName, group`) if they already exist.

Disable importing existing GI () if they already exist.

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/model/SchemaModel.js

When we drag&drop a workflow (append) from the palette to the current workflow its information are not imported. In this PR, we add the elements that are not currently defined (No Name, or No Project or No Description, No GI or partial GI) to the current workflow.
So it also means to add the GI not yet defined.

import workflow information (GI, Variables, Name, Project, Descriptio…n) when we drag&drop it from the palette

---

app/templates/02_task_dependencies.xml
app/templates/05_workflow_replication.xml
app/templates/06_workflow_loop.xml
app/templates/07_workflow_branch.xml
app/templates/SubmitJobAndWait.xml
app/templates/SubmitJobNoWait.xml
app/templates/submit_and_wait_for_any.xml
app/templates/wait_for_any.xml
app/templates/wait_for_any_replicate.xml
test/json-server-data/buckets-resources/bucket-id-1000-res.json
test/json-server-data/buckets-resources/bucket-id-1001-res.json
test/json-server-data/objects-revisions/2min-cron-rev.json
test/json-server-data/objects-revisions/cloud-automation-rev.json
test/json-server-data/objects-revisions/data-mgnt-rev.json
test/json-server-data/objects-revisions/distrib-comput-rev.json
test/json-server-data/objects-revisions/docker-exec-env-rev.json
test/json-server-data/objects-revisions/proactive-delete-rev.json
test/json-server-data/objects-revisions/proactive-rev.json

In this PR, we update the notation of the GI variable "pca.action.icon" to "workflow.icon".

change pca.action.icon to workflow.icon in all workflows

---

app/index.html
app/scripts/proactive/view/dom.js
app/styles/studio.css

- adding tooltip for Other Keys supported by the editor
- fixing display on laptops

New CodeMirror Editor

---

app/scripts/proactive/model/script/ScriptCode.js
app/scripts/proactive/model/script/SelectionScript.js
app/scripts/proactive/templates/task-template.html
app/styles/studio.css

- fix model populate regarding script code arguments
- fix task export xml
- add help tooltip for selection script type
- add margin top to argument labels

Refactoring of script model management and presentation

---

app/scripts/proactive/view/CatalogPublishView.js

URL in 'links' of the response is always 'localhost'

Building new URL with commit time raw

---

app/templates/SubmitJobAndWait.xml

SubmitJobAndWait

---

app/templates/php_script.xml

Intention:
- The PHP Task should succeed when executed as default
Description:
- Add PHP code in the pre-script
- User which drags the PHP task and executes it, will have the task working immediately with default settings.

Create default php-script for PHP task in pre script.

---

app/scripts/proactive/templates/catalog-get-revision-description.html
app/scripts/proactive/templates/catalog-get-revision.html
app/scripts/proactive/view/CatalogGetView.js
app/templates/execute_action_PCA_service.xml
app/templates/submit_job_and_wait.xml
app/templates/submit_job_no_wait.xml
app/templates/trigger_PCA_service.xml

In this PR, we display the username that committed the objects/wfs to catalog in the import object from catalog modals.

Display committed by username when importing from catalog

---

app/templates/submit_and_wait_for_any.xml
app/templates/submit_job_and_wait.xml
app/templates/submit_job_no_wait.xml

Update Distributed_Computing_Pi wf name from `Distributed_Computing_PI` to `Distributed_Computing_Pi`

Update Distributed_Computing_Pi wf name

---

app/scripts/proactive/view/dom.js

- Do not close editor window when clicking outside the modal.

Work on #628 Editor user experience improvements

---

app/scripts/proactive/view/dom.js

Fix job submission issue in studio

Use textarea in variable values

---

app/scripts/proactive/config.js
app/scripts/proactive/view/dom.js

- wrong code mirror mode was defined
- better usage of lowercase

Fix handling of R mode

---

app/scripts/proactive/config.js
app/scripts/proactive/view/WorkflowView.js

- fix the R language config (importing a R script was broken)
- allow selecting the loop target on the same task

Small fixes in studio

---

app/index.html
app/scripts/proactive/app.js
app/scripts/proactive/config.js
app/scripts/proactive/rest/studio-client.js
app/scripts/proactive/router.js
app/scripts/proactive/templates/presets-item.html
app/scripts/proactive/templates/presets-set-preset.html
app/scripts/proactive/view/CatalogSetTemplatesBucketView.js
app/scripts/proactive/view/PaletteView.js
app/scripts/proactive/view/SetPresetView.js
app/scripts/proactive/view/WorkflowView.js
app/scripts/proactive/view/dom.js
app/styles/studio.css

In this PR, we add a new feature to the studio called the Presets.
It allows to load a predefined set of buckets in the Palette toolbar.
More precisely, this PR:
1) Refactors the old palette rendering fashion based on main+secondary bucket menues
2) Adds a preset definition in the config.js
3) Adds a preset loading menu from View=>Change Studio Preset
4) Adds a new modal for loading presets.
7) Beautifies many files (HTML, javascript)

Add Presets feature

---

app/index.html
app/styles/studio.css

In this PR we change the *false* corporate color with the true corporate orange color (#E86D1F)

Update corporate-orange color

---

app/index.html
app/scripts/proactive/app.js
app/scripts/proactive/model/Job.js
app/scripts/proactive/model/SchemaModel.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/view/dom.js

Bug: when trying to drag & drop a task or a workflow from the ML buckets the position doesn't change for the task of workflow that has its own position before.

Fix a bug: drag & drop a task or a workflow

---

app/index.html
app/scripts/proactive/view/TaskView.js
app/scripts/proactive/view/ViewWithProperties.js
app/scripts/proactive/view/WorkflowView.js
app/scripts/proactive/view/dom.js
app/styles/studio.css

1- Able to do  Ctrl+X
2- Create a menu: Add Copy, Paste, Cut, select All and delete,

Studio:: Add Copy, Paste, Cut, select All and delete entries in menu Edit

---

app/scripts/proactive/templates/job-variable-template.html

When the workflow variable has the type PA:HIDDEN, its value is hidden during input.

feat: add workflow variable type `PA:HIDDEN`

---

app/scripts/proactive/view/dom.js

- before task variables are populated, sort the tasks alphabetically.

Sort tasks in workflow submission form

---

app/scripts/proactive/templates/job-variable-template.html

- fetch the model content dynamically when building the form
- replace the current model

Allow PA:MODEL_FROM_URL dynamic replacement in workflow submission form

---

app/scripts/proactive/config.js

- update using latest fork env script code

Change docker fork environment script:

---

app/scripts/proactive/config.js
app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/view/dom.js

Fix paths in documentation urls

---

README.md
app/scripts/proactive/rest/studio-client.js
app/scripts/proactive/templates/login-template.html
app/styles/studio.css
test/json-server-data/mock-scheduler-rest.js
test/ui/specs/login.js

The objective of this card is to enable portal access restrictions in the studio.

Studio:: Portal access restriction

---

app/scripts/proactive/view/TaskView.js

Display the description of the task when the use move the mouse over the task name.

 Add tooltips to show task descriptions in canvas

---

app/index.html
app/scripts/proactive/templates/login-template.html
app/styles/studio.css

1- Put the portal logo on the left, and description on the right
2- Put "more options" in the center

Login page

---

app/scripts/proactive/view/dom.js

Bug:: The layout changes when we import a work from catalog first time, and then we add a task.

Fix a bug:: changing the position of the tasks

---

app/styles/login.css

previous color wasn't the same as the logo

update text style with the right color

---

app/index.html
app/scripts/proactive/templates/file-browser-template.html
app/scripts/proactive/templates/job-variable-template.html
app/scripts/proactive/view/FileBrowserView.js
app/scripts/proactive/view/GlobalFileView.js
app/scripts/proactive/view/JobVariableView.js
app/scripts/proactive/view/ThirdPartyCredentialView.js
app/styles/studio.css

For the variable PA:GLOBAL_FILE and PA:USER_FILE, add the modal to browse the corresponding data space files (support upload, delete file, create new folder), and select a data space file as the variable value.

Add file browser modal for showing dataspace files

---

app/scripts/proactive/app.js
app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/router.js
app/scripts/proactive/view/CatalogGetView.js

additionnally: 
Fix case issue on PA:HIDDEN

Allow importing a specific catalog object revision

---

app/index.html
app/scripts/proactive/templates/file-browser-template.html
app/scripts/proactive/view/FileBrowserView.js
app/styles/studio.css

- Improve global/user space button icon
- Add description of global/user dataspace in the dataspace file browser
- Change 'Cancel' button text to 'Close' when the file browser is not opened for a specific variable.

improve file browser modal icon, description and close button

---

app/scripts/proactive/config.js

Without setting this variable, singularity 3 does not work properly.

Singularity fork environment : fix XDG_RUNTIME_DIR variable

---

app/index.html

Relocate custom brand logo to the left of AD shortcut

---

app/index.html

Brand logo 2

---

app/scripts/proactive/templates/job-variable-template.html
app/scripts/proactive/view/dom.js

The objective is to consider the value of $B as the PA model of A as well in submission modals and show its PA_MODEL name or UI controls (boolean switches, etc)

Studio:: variables substitution

---

app/scripts/proactive/model/SchemaModel.js

Workflow Studio: Avoid duplicating workflow variables with the same name

---

app/scripts/proactive/templates/file-browser-template.html
app/scripts/proactive/view/FileBrowserView.js

- add file permissions in the form "rwx" to file list
- add check box to hide/show files or directories starting with .
- improve error messages in case of unauthorized file or folder operations

File Browser : add file permissions and hidden files

---

app/scripts/proactive/model/CatalogBucketCollection.js
app/scripts/proactive/model/CatalogObjectCollection.js
app/scripts/proactive/view/CatalogGetView.js
app/scripts/proactive/view/JobVariableView.js
app/scripts/proactive/view/dom.js

The modal of selecting catalog object variable value, now shows the objects based on the filters (kind and contentType) defined in the variable model.

Workflow var PA:CATALOG_OBJECT modal add filters for kind and contentType

---

app/scripts/proactive/view/CatalogGetView.js

- fix the bug: in catalog object modal when change bucket showAll checkbox, the contentType filter is not correctly updated;
- disable select button when no catalog object is selected.

fix catalog object modal 

---

app/scripts/proactive/templates/job-variable-template.html
app/scripts/proactive/view/dom.js

Also, add Main Variables label to empty groups

Remember which tasks were toggled when the variables are validated.

---

app/scripts/proactive/view/CatalogPublishView.js

My last PR caused this issue https://github.com/ow2-proactive/studio/pull/844

Publish wf to catalog is broken if we publish twice

---

app/scripts/proactive/templates/file-browser-template.html
app/scripts/proactive/view/FileBrowserView.js

- add form
- change the height of the Search button
- make the filter input larger

refactor-filter-dataSpace-file-browser

---

app/scripts/proactive/view/TaskView.js

no need to call this function in this PR #838

fix bug: copy/past doesn't work

---

app/scripts/proactive/view/WorkflowView.js
app/scripts/proactive/view/dom.js

- previous implementation was using jQuery.extend to clone existing models, but the cloned model was keeping original listener, meaning that a modifying a new task could modify also the original
- new implementation perform an export to xml of a task, and then reparse into a new backbone object

Fix copy/paste model handling

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js

Add new tabs 'Task Variables' and 'Generic Info' for the task properties to be coherent as workflow properties.

Add new tabs for the task properties to be coherent as workflow properties

---

app/scripts/proactive/view/ViewWithProperties.js

Add a title to specify the left-side panels is showing "Workflow Parameters" / "Task Parameters" / "Control Flow Parameters" at the top of the properties

Add title Workflow / Task / Control Flow Parameters at top of properties

---

app/scripts/proactive/view/dom.js
app/styles/studio.css

put on the same line:
<Icon> Pin to Open <Title: Scripts being Called by Current ...>

pop-lines header

---

app/scripts/proactive/view/dom.js
app/styles/studio.css

- fix the issue 
- remove the display of the header when there is no item to show
- well positioned the header: put the icon on the left

Fix: the title disappears when we move the drop down

---

app/scripts/proactive/model/JavaExecutable.js
app/scripts/proactive/model/Job.js
app/scripts/proactive/model/SchemaModel.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/model/script/FlowScript.js
app/scripts/proactive/templates/task-template.html
app/scripts/proactive/view/TaskView.js
app/scripts/proactive/view/ViewWithProperties.js
app/scripts/proactive/view/dom.js
app/scripts/proactive/view/xml/TaskXmlView.js
app/styles/studio.css
test/ui/specs/forkExecutionEnvironment.js

Changing the name of the schema attributes triggers all field listeners which removed the loop

fix-loop-disappeared-bug

---

app/scripts/proactive/model/CatalogBucketCollection.js
app/scripts/proactive/model/CatalogObjectCollection.js
app/scripts/proactive/view/JobVariableView.js
app/scripts/proactive/view/TaskView.js

- add encodeUriComponent to prevent url issues
- remove % replacement

Fix pattern usage in object name filters

---

app/scripts/proactive/rest/studio-client.js
app/scripts/proactive/templates/login-template.html
app/scripts/proactive/view/LoginView.js
app/styles/login.css

change-error-message-when-invalid-domain

---

app/scripts/proactive/rest/studio-client.js
app/scripts/proactive/view/LogoutView.js

show-error-label-when-server-is-unresponsive

---

app/scripts/proactive/rest/studio-client.js
app/scripts/proactive/templates/login-template.html
app/scripts/proactive/view/LogoutView.js

show-error-message-when-server-is-unresponsive

---

Gruntfile.js
build.gradle

Also, use bgShell tasks in grunt test:ui:dev configuration

Exclude bower.json and package.json from the dev archive

---

app/scripts/proactive/templates/job-variable-template.html

Fix advanced variables layout regression

Fix css layout regression

---

app/scripts/proactive/view/JobVariableView.js
app/scripts/proactive/view/WorkflowVariablesView.js

model value was not retrieved from the correct html attribute

Fix PA:CATALOG_OBJECT modal filtering

---

app/scripts/proactive/model/Task.js

Check if FlowScript exists and create only if not.

Preserve Flow script if it exists when connecting loop to another task

---

app/scripts/proactive/model/GroupByProjectMixin.js
app/scripts/proactive/templates/workflow-list.html
app/scripts/proactive/view/WorkflowListView.js

Change search wf layout
