ow2-proactive/studio

test/ui/commands/login.js
test/ui/nightwatch.json
test/ui/specs/dependencies.js
test/ui/specs/forkExecutionEnvironment.js

Remove hardcoded timeouts. Add a pause into the Docker Env test.
All hardcoded timeouts are removed. So that every waitFor takes the globally configured timeout.
The Docker Env tests fail on the server but run locally. Furthermore they run locally against the current trydev. Whereas they fail on the server against trydev. The pause is intended to fix this behavior.

Remove hardcoded timeouts. Add a pause into the Docker Env test.

---

test/ui/commands/freshWorkflow.js
test/ui/commands/hideMenu.js
test/ui/commands/showMenu.js
test/ui/nightwatch.json

Prevent the Studio test run into an infinite loop of failures.
The selenium tests have some parts, which retry in an infinite loop. That can and did let the test run into an infinite loop, blocking jenkins and flooding the file system with error reports. To prevent that from happening again, a maximum number of tries is introduced.

Prevent the Studio test run into an infinite loop of failures.

---

test/ui/specs/forkExecutionEnvironment.js

Wait for moving element to stop to perform a click.
The Fork Environment tab seems to move, while the click is performed. The assumption comes from the fact that the selenium test fails with element not clickable but not reproducible in a virtual machine (much slower one).

Wait for moving element to stop to perform a click.

---

test/ui/specs/forkExecutionEnvironment.js

Move to Element before click.
That the forefox driver behavior changed, so an element must be visible before it is clickable. The curser is moved (and the menu is scrolled) to the element before it is clicked.

Move to Element before click.

---

app/scripts/proactive/model/Task.js

Change description of fifth state of onTaskError to default '(defined at job level)'.

Change description of fifth state of onTaskError to default '(defined at job level)'.

---

test/ui/commands/checkExport.js

The studio test parses the xml in the export window. The parsing method looks for the jobdescriptor 3.3. We updated the jobdescriptor to 3.4, so this test needs to be adjusted as well.

Fix failing "Pull out a dependency" Studio test

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/model/SchemaModel.js

Imported Workflows need to be converted to not change their behavior.
Workflows which had CancelJobOnError='true' where converted into onTaskError='continueJobExecution'. That changed the error behavior of tasks.
The SchemaModel got a conversion method, which does the conversion.

Imported Workflows need to be converted.

---

app/scripts/proactive/templates/script-template.html

Tabs spaces prevents Python (which expect correct formatting) to work correctly.

Fix bug #2547 Python script task fails to execute

---

app/scripts/proactive/rest/studio-client.js

By adding judgement about invalid login and password

Fixes #278: Message for authentication failure is misleading

---

app/scripts/proactive/view/LoginView.js

Template content associated to login view was not always appended to the
document object while rendering the login view with Backbone.js. Also, binding
was too late for some of the cases that were already handled. As a consequence,
the event that is defined for the Submit button was not registered by
Backbone.js and thus not triggered.
This patch fixes ow2-proactive/studio#312.

Append template content to document object at first during rendering

---

app/index.html

- Sub menus provide more space in the navigation bar, revert the previously added padding
@sophiesongge Thank you for pointing out that we changed the padding recently so that the "big" menu fits. 
This PR reverses the padding change, because the sub menus reduce the menu size significantly.
Here is the Studio with padding: 
Here is the new version without padding:

Change padding size due to su menus

---

app/scripts/proactive/view/dom.js

Set documentation link to dev when SNAPSHOT version
Problem:
- The studio portal links to www.doc.activeeon.com/
- the $.getScript is asynchronous, so documentation link is set before the latest, now dev addition was set
Solution:
- Move the $("#documentationLinkId").attr("href", result); into the $.getScript

Set documentation link to dev when SNAPSHOT version

---

test/ui/specs/workflow.js

The testcase Workflow with job variable was failing because it was actually login out before doing the rest of the checks. In a local environment this doesnt happen because a notification appears on top of the log out button but with latency, the notification has enough time to disappear so the way is clear to log out. This fix is to remove the unecessary click to log out as the test is not finished.

Fix failing test

---

app/scripts/proactive/view/dom.js

- use the isEmptyObject jquery method to test that the jobVariables object is empty

submission form : job with no variables should not pop up the execution form

---

app/scripts/proactive/model/utils.js

As the problem is difficult to reproduce, try to remove problems which could occur if inherited = 'undefined' string

tentative fix for #357 : Inherited task variable checkbox is randomly turning on

---

app/scripts/proactive/templates/task-template.html

This change resolves #357 and partially addresses #410 (which will come next).
Additionally fixes the random appearance of "model" attribute in the task variable tag of the XML, even when the value of "model" is empty.

 Fix bug of Inherited task variable checkbox is randomly turning on

---

app/index.html
app/scripts/proactive/model/CatalogRestBucket.js
app/scripts/proactive/view/CatalogGetView.js
app/scripts/proactive/view/dom.js

When opening "Get a Workflow from the Catalog" and "Publish current Workflow to the Catalog" windows, we ask server for every workflow of every buckets to display them. This takes too much time so we will only load buckets and once a bucket is selected, we will load its workflows.

Improve performance of Catalog loading in the Studio

---

build.gradle
gradle.properties

If the property customizableSquaredLogoLocation will be set to an url, the studio placeholder image will be overwritten with the file behind that url.

Allow to change logo in studio

---

app/scripts/proactive/view/PaletteView.js

Extra catalog palette's items were only draggable, not clickable. They should also be clickable

Bug fix: extra catalog palette's item clickable

---

app/scripts/proactive/model/CatalogWorkflowCollection.js
app/scripts/proactive/model/ForkEnvironment.js
app/scripts/proactive/model/NativeExecutable.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/model/utils.js

On the properties panel, lists that contain strings (Jvm Arguments, Additional Classpath & Arguments for native task implementation)  have the same remove button as other lists 
& only workflows in templates menu

Lists that contain strings have the same remove button as other lists

---

app/scripts/proactive/view/TaskView.js

In this PR, we fix the issue described in #488  that prevents nameless tasks from being removed unless they get a name.
The applied solution consists in notifying the user as shown in the attached screenshot.
**Note:** We followed the same behaviour as when the user gives a duplicate name to the task.
(Of course, the issue does not affect the scheduler because workflows with nameless tasks cannot be submitted to the scheduler).

FIX issue #488 related to empty task names

---

app/scripts/proactive/app.js
app/scripts/proactive/view/WorkflowListView.js
app/scripts/proactive/view/dom.js

It is not possible to import a workflow from catalog using URL feature : it would replace the current workflow. When entering a URL for workflow import and the workflow is opened, the page stays the same and the action is ignored.

 Fixing bug when importing from catalog and a workflow is already opened

---

app/scripts/proactive/model/Task.js

The commit fixes this issue https://github.com/ow2-proactive/studio/issues/505
It addresses also another bug: after deleting the task.documentation GI, clicking again on the task shows the deleted value.

Fix task.documentation link after GI removal #505

---

app/scripts/proactive/model/ForkEnvironment.js

Removed the initialization of the model which was overwriting already entered script.

Fix for #576 Fork Environment Code and Language are lost when set to Docker

---

app/scripts/proactive/templates/catalog-publish-description.html
app/scripts/proactive/view/CatalogGetView.js
app/scripts/proactive/view/CatalogPublishView.js

-Script imports were not saved
-Removing unsused kind when publishing a revision
-Fix bug: impossible to submit pca workflow revisions

Changes after validation

---

app/scripts/proactive/rest/studio-client.js

logout view (so user name) was built before setCurrentUser was finished. Adding 'async' fixed the problem, now we wait for the currentUser request to be done to start building the logout view

Fixing issues #596 & #568: Wrong user displayed

---

app/scripts/proactive/view/CatalogGetView.js
app/scripts/proactive/view/dom.js

In this PR, we make sure that imported scripts from the catalog are displayed in a relative way in the script URL text field using the `${PA_CATALOG_REST_URL}` instead of an absolute URL.
We also make the edit script action compatible with such relative urls

Make imported catalog scripts urls relative

---

app/index.html
app/scripts/proactive/view/PaletteView.js
app/scripts/proactive/view/WorkflowView.js
app/scripts/proactive/view/dom.js
app/styles/studio.css

In this PR:
- Add pin functionality to pin/unpin the palette(sticky/relative position).
- Add button to add buckets to the palette easily
- Reconstruct the tools panel into a 3 div column design instead of cell design
- New buckets are added in a new line if width is insufficient
- fix old bugs like dragging an element under the left panel
- improve the layout for multiple things

Improve Calalog palette with new features and bug fixes

---

app/scripts/proactive/router.js

In this PR, we update the router.js to allow accessing a specific Palette Preset using a URL that contains the preset ID. (the previous url was semantically wrong and the preset loading mechanism didn't follow)

Allow direct access to palette presets using a URL

---

app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js
app/scripts/proactive/rest/studio-client.js
app/scripts/proactive/view/dom.js

When the workflow designer create a workflow variable of the type `PA:CREDENTIAL`, its default value should not be checked whether exists in the third-party credentials.
Therefore, when sending validation request in case of variable creation and automatic validation (i.e., checking default value cases), the validation request should not contain sessionid.

fix [PA:CREDENTIAL]: disable validity check during creating wf

---

app/index.html
app/scripts/proactive/templates/job-variable-template.html
app/scripts/proactive/templates/third-party-credential-template.html
app/scripts/proactive/view/JobVariableView.js

Improve the UI of third-party-credentials management modal:
- grey out the underlying modal (its parent modal: execute-workflow-modal)
- centralize horizontally its parent modal execute-workflow-modal

Fix third-party-credentials management modal

---

app/index.html
app/scripts/proactive/view/JobVariableView.js

zIndex modification should only apply to the 3rd-party-cred modal to avoid impact catalog script import

fix gray layout when import selection script from catalog

---

app/scripts/proactive/config.js

- make it cross-platform (windows or linux)
- use new java pre command format (more robust, tolerate paths with spaces)
- use current java installation by default (allows using generic containers without java)
- mount cache space

Improve docker fork environment template

---

app/scripts/proactive/rest/studio-client.js
app/scripts/proactive/templates/third-party-credential-template.html
app/scripts/proactive/view/ThirdPartyCredentialView.js
app/scripts/proactive/view/dom.js
app/styles/studio.css

- Fix escape 3rd-party-creds key for path param in the creds add/remove request.(fixed with `encodeURIComponent`)
- Fix: when import/add the workflow from xml file, we should disable check the validity of PA:CREDENTIAL variables.
- Improve: beautify 3rd-party-cred modal in studio (ref BeautifiedModalAdapter) and improve ui when key is too long
- change add/remove button color
- align key/creds between creds table and add-cred div
- break long key to multiple lines.

Fix and improve third-party credentials management

---

app/libs/backbone-forms/distribution.amd/backbone-forms.js
app/libs/backbone-forms/distribution/backbone-forms.js
app/scripts/proactive/model/Job.js
app/scripts/proactive/model/Task.js

- When creating or editing a PA:HIDDEN variable in the workflow, the server response contains the data in encrypted format. Use this value to store it in the workflow instead of clear text data.
- like often, backbone-forms did not provide the necessary feature, so I resolved on modifying backbone-forms to give access to the current form when validating a list entry. This allows the validation to modify the value when the form is submitted.

Add automatic encryption for PA:HIDDEN variables

---

app/scripts/proactive/model/Task.js
app/scripts/proactive/view/WorkflowView.js

When changed if/else branch connected target task in studio, controlFlow target (if/else/continuation) should be correctly updated in the workflow definition. 
Previously, it always change the "continuation" target to the new associated task, even when it's actually "if" or "else" connection updated in front-end. So it caused inconsistency between workflow diagram and its model definition.
Fix:
- retrieve the updated branch from the connection label, then call the corresponding setif/setelse/setcontinuation function to update task model.
- setif should only initialize the script model to `new FlowScript()` when the control flow "if" is newly set, so that updating if branch target won't erase existing controlFlow script.

fix issue #675 for updating if branch

---

app/scripts/proactive/view/FileBrowserView.js

Currently, having a file/folder name containing colons will cause a [vfs bug](https://issues.apache.org/jira/browse/VFS-398) when browsing files. 
This PR is to do a temporary workaround for this bug: disallow colon in uploaded file and created folder in front-end.

file browser disallow colon in uploaded file and created folder

---

app/scripts/proactive/view/dom.js

Control if the original variable value does not contain a pattern reference to another variable $some_var.
If it does, then replacing the value can lead to mistakes if the referenced variable is changed by the user again
in the submission form.

Job submission check : replace variable value only when it does not reference another variable

---

app/scripts/proactive/templates/third-party-credential-template.html
app/scripts/proactive/view/ThirdPartyCredentialView.js

In the modal of managing 3rd-party-credentials when submitting a workflow with PA:CREDENTIAL variables, add a checkbox "Multiline credential" to allow the user to input the multi-lines credential value by switching between the password input (for single line credential) and textarea (for multi-lines credential).

Support to add multi-lines credential value in 3rd-party-credential modal

---

app/scripts/proactive/templates/catalog-publish-description-first.html
app/scripts/proactive/view/CatalogPublishView.js

- When publish a workflow, make its kind property editable. 
- When the workflow has the generic info `pca.states` and `pca.service.id` specified, change its default kind value to workflow/psa.

publish workflow: editable kind and correct default kind workflow/psa

---

app/scripts/proactive/templates/login-template.html

This is to prevent an issue being raised by a PenTest, though it does not change anything technically as the form itself is not used to perform the REST login request.

Change login form method to post

---

app/templates/script_cmd.xml

This is to better handle international characters in script output

Add chcp to cmd template
